/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistema.gestion.hospitalaria.interfaz;

/**
 *
 * @author juank
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscarPacientes = new javax.swing.JButton();
        BuscarMedico = new javax.swing.JButton();
        BuscarEnfermeros = new javax.swing.JButton();
        AsignarCita = new javax.swing.JButton();
        EliminarCita = new javax.swing.JButton();
        ReprogramarCita = new javax.swing.JButton();
        etiquetaOpciones = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        BuscarPacientes.setBackground(new java.awt.Color(102, 255, 102));
        BuscarPacientes.setText("Buscar / Registrar Pacientes");
        BuscarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPacientesActionPerformed(evt);
            }
        });

        BuscarMedico.setBackground(new java.awt.Color(102, 255, 102));
        BuscarMedico.setText("Buscar / Registrar Medicos");
        BuscarMedico.setPreferredSize(new java.awt.Dimension(175, 23));
        BuscarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarMedicoActionPerformed(evt);
            }
        });

        BuscarEnfermeros.setBackground(new java.awt.Color(102, 255, 102));
        BuscarEnfermeros.setText("Buscar / Registrar Enfermeros");
        BuscarEnfermeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarEnfermerosActionPerformed(evt);
            }
        });

        AsignarCita.setBackground(new java.awt.Color(102, 255, 102));
        AsignarCita.setText("Asignar Citas Medicas");
        AsignarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarCitaActionPerformed(evt);
            }
        });

        EliminarCita.setBackground(new java.awt.Color(102, 255, 102));
        EliminarCita.setText("Eliminar Citas Medicas");
        EliminarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCitaActionPerformed(evt);
            }
        });

        ReprogramarCita.setBackground(new java.awt.Color(102, 255, 102));
        ReprogramarCita.setText("Reprogramar Citas Medicas");
        ReprogramarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReprogramarCitaActionPerformed(evt);
            }
        });

        etiquetaOpciones.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        etiquetaOpciones.setText("Haga click en una de las opciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(BuscarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuscarMedico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscarEnfermeros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EliminarCita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AsignarCita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReprogramarCita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(etiquetaOpciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AsignarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarEnfermeros, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReprogramarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPacientesActionPerformed
        
        PanelPacientes ventanaPacientes = new PanelPacientes();
        Grafica.irAPanel(this, ventanaPacientes);
    }//GEN-LAST:event_BuscarPacientesActionPerformed

    private void BuscarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarMedicoActionPerformed
        PanelDoctores ventanaDoctores = new PanelDoctores();
        Grafica.irAPanel(this, ventanaDoctores);
    }//GEN-LAST:event_BuscarMedicoActionPerformed

    private void BuscarEnfermerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarEnfermerosActionPerformed
        PanelEnfermeros ventanaEnfermeros = new PanelEnfermeros();
        Grafica.irAPanel(this, ventanaEnfermeros);
    }//GEN-LAST:event_BuscarEnfermerosActionPerformed

    private void AsignarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarCitaActionPerformed
        PanelAsignarCita ventanaAsignarCita = new PanelAsignarCita();
        Grafica.irAPanel(this, ventanaAsignarCita);
    }//GEN-LAST:event_AsignarCitaActionPerformed

    private void EliminarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCitaActionPerformed
        PanelEliminarCita ventanaEliminarCita = new PanelEliminarCita();
        Grafica.irAPanel(this, ventanaEliminarCita);
    }//GEN-LAST:event_EliminarCitaActionPerformed

    private void ReprogramarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReprogramarCitaActionPerformed
        PanelReprogramarCita ventanaReprogramarCita = new PanelReprogramarCita();
        Grafica.irAPanel(this, ventanaReprogramarCita);
    }//GEN-LAST:event_ReprogramarCitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AsignarCita;
    private javax.swing.JButton BuscarEnfermeros;
    private javax.swing.JButton BuscarMedico;
    private javax.swing.JButton BuscarPacientes;
    private javax.swing.JButton EliminarCita;
    private javax.swing.JButton ReprogramarCita;
    private javax.swing.JLabel etiquetaOpciones;
    // End of variables declaration//GEN-END:variables
}
